apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: rails-app-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: rails-app
    spec:
      containers:
        - name: rails-app
          image: sarumathy/ruby_app:latest
          ports:
            - containerPort: 3000
           env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: rails-app-secrets
                  key: database-url
            - name: SECRET_KEY_BASE
              valueFrom:
                secretKeyRef:
                  name: rails-app-secrets
                   key: secret-key-base