apiVersion: v1
kind: Secret
metadata:
  name: rails-app-secrets
type: Opaque
data:
  secret-key-base: NTljZjE2MmZmNGI0YzBlN2UxZTc0NWRiNGEzNTlhMmU3ZTBiM2I2MTliMmM3NDI2YmQ2M2MzOTE2ZTU2ZDUzMzQwNzBjNDgwMmY2MDc4MmU3MTE1NDY2NzQzZmMzZTAyZTc2MDU1YjQwYjM2Mjg4Mjg4N2MyNDczYWNhZjNjNjY=
  database-url: cG9zdGdyZXM6Ly9wb3N0Z3Jlczp0ZXN0QHBvc3RncmVzOjU0MzIvb3Blbi1mbGlnaHRzX2RldmVsb3BtZW50