version: "3.7"

services:
  ruby_dev:
    build: .
    container_name: ruby_container
    ports:
      - "3000:3000"
    volumes:
      - ./:/home/app
    depends_on:
      - postgres  

  postgres:
    image: postgres
    container_name: postgres_container
    ports:
      - "5432:5432" 
    environment:
      POSTGRES_DB: open-flights_test
      POSTGRES_PASSWORD: password

